        <div id="loginbox">  
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <form id="loginform" class="form-vertical"  action="login.php" method="post">
                <div class="control-group normal_text"> 
                    <h3>
                      <img src="./public/img/logo.png"  width="250" alt="Logo"/>
                    </h3></div>
                <div class="control-group"> 
                    <div class="controls">
                        <div class="main_input_box">
                            <span class="add-on"><i class="icon-user"></i></span><input type="text" name="userName" placeholder="Username" />
                        </div>
                    </div>
                </div>
                <div class="control-group">
                    <div class="controls">
                        <div class="main_input_box">
                            <span class="add-on"><i class="icon-lock"></i></span><input type="password" name="pass" placeholder="Password" />
                        </div>
                    </div>
                </div>
                <div class="form-actions">
<!--                    <span class="pull-left"><a href="#" class="flip-link btn btn-inverse" id="to-recover">Lost password?</a></span>-->
                    <span class="pull-right"><input type="submit" class="btn btn-info" value="Login" /></span>
                </div>
            </form>
        </div>    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    