<div class="row">
	<div class="col-md-12">
<div class="btn-group pull-right">
</div>
<div class="card">
  <div class="card-header" data-background-color="blue">
      <h4 class="title">Tickets</h4>
  </div>
  <div class="card-content table-responsive">
       <a href="newTicket.php" class="btn btn-info">Nuevo Ticket</a>
		<?php
		   if(!empty($datosSoporteClient)){
			// si hay usuarios
			?>

			<table id="serviceClient" class="display " cellspacing="0" width="100%">
			<thead>
	        <th >#</th>
                <th >Tipo de Servicio</th>
                <th>Departamento</th>
                <th>Personal que realiza Servicio</th>
                <th>Fecha de Solicitud</th>
                <th>Status</th>
			</thead>
                      
			<?php
  
			foreach($datosSoporteClient as  $datos){
                          $i++;
				?>
				<tr>
			<td><?=  $datos['servicios_id']?></td>
                        <td  data-toggle="tooltip" title="<?= $datos['observaciones']?>" ><?= $datos['servicio'] ?></td>
                        <td><?= $datos['nombre_depa'] ?></td>
                        <td><?= $datos['asignacion'];  ?> </td>
                        <td><?= $datos['fecha_servicio_inicio'];  ?> </td>
                        <td><?= ($datos['status']== 1)?"<font color='#F10A0A'>Abierto</font>": "" ,
                                ($datos['status']== 2)?"<font color='#FF9700'>En Proceso</font>": "" ,
                                ($datos['status']== 3)?"<font color='#079000'>Terminado</font>": "" ;?>
                         </td>
                   
				</tr>
	      			<?php

			}
			?>
			</table>
			</div>
			</div>
			<?php

}else{
			echo "<p class='alert alert-danger'>No hay Servicios</p>";
		}


		?>


	</div>
</div>