<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Dashboard - Bootstrap Admin Template</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<meta name="apple-mobile-web-app-capable" content="yes">
<link href="./public/cssOld/bootstrap.min.css" rel="stylesheet">
<link href="./public/cssOld/bootstrap-responsive.min.css" rel="stylesheet">
<link href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600"
        rel="stylesheet">
<link href="./public/cssOld/font-awesome.css" rel="stylesheet">
<link href="./public/cssOld/style.css" rel="stylesheet">
<link href="./public/cssOLD/pages/dashboard.css" rel="stylesheet">
        <link href="./public/cssOLD/pgwmodal.min.css" rel="stylesheet">
        <link href="./public/cssOLD/pgwmodal.css" rel="stylesheet">
<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>
<body>
     <div class="modal inmodal fade" id="myModal6" tabindex="-1" role="dialog"  aria-hidden="true">
                                <div class="modal-dialog modal-sm">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                                            <h4 class="modal-title" id="alerta">Modal title</h4>
                                        </div>
                                        <div class="modal-body" id="alertar">
                                           
                                        </div>
                                        <div class="modal-footer">
<!--                                            <button type="button" class="btn btn-white" data-dismiss="modal">Cerrar</button>-->
                                            
                                        </div>
                                    </div>
                                </div>
                            </div>
    
    
    
    
    
    
    
    
    
    
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container"> <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"><span
                    class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span> <a class="brand" href="index.html"><img src="./public/img/logo.png"  alt="Smiley face"> </a>

      <!--/.nav-collapse --> 
    </div>
    <!-- /container --> 
  </div>
  <!-- /navbar-inner --> 
</div>
<!-- /navbar -->
<div class="subnavbar">
  <div class="subnavbar-inner">
    <div class="container">

 
    </div>

    <!-- /container --> 
  </div>
  <!-- /subnavbar-inner --> 
</div>
<!-- /subnavbar -->
<div class="main">
  <div class="main-inner">
    <div class="container">
      <div class="row">
          <div id="panelAgentes">     
                   <div class="span12">
          <?php if (!empty( $audiosTotales)) { ?>
                        <form  action="audiosAsignados.php" id="asigAudios" name="asigAudios" method="POST"> 
<table id="tablaAsignacion"  class="display" cellspacing="0" width="80%">
    <thead>
                            <tr role="row">
                                <th>#</th>
                                <th>Nombre campana</th> 
                                 <th>Fecha Gestion</th>
                                 <th>Agente</th>
                                  <th>Numero Marcado</th>
                                   <th>Tipificacion</th>
                                   <th> </th>
                               
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                               
                                foreach ( $audiosTotales as $datos) {
                                          $i++;

                                    ?>
                                    <tr>
                                        <td > <?php echo $i; ?> </td>
                                        <td><?php echo  $datos['nombre_campana']; ?></td>
                                        <td><?php echo  $datos['fecha_gestion']; ?></td>
                                        <td><?php echo  $datos['agente']; ?></td>
                                        <td><?php echo  $datos['numero_marcado']; ?></td>
                                         <td><?php echo  $datos['status_registro']; ?></td>
                                         <td style="width: 4.1%; width:50px;">
                                             <input type="hidden" name="contador" value="<?=$i?>" id="contador">
												<div class="checkbox radio-margin">
													<label>
														<input type="checkbox" value="<?= $datos['id'];?>"  id="idAudio"  name="idAudio<?=$i?>">
														
													</label>
												</div>
											
											</td>    
                                    </tr>
        <?php
    }

?>

            
                        </tbody>
                    </table>
                 <div class="form-group">
                                     <div id="buttonGuardar" name="buttonGuardar">
                                         <center>
                                             <input type="hidden" name="userID" id ="userID" value="<?=$userNamer?>">
                                    <button class='btn btn-danger' id='btnCerrar' onclick='cerrar()' name='btnCerrar'  type='button'>Cerrar</button>    
                                 <button type="submit" class="btn btn-primary"  id="buttonAsignar" name="buttonAsignar" >
                                      Asignar Audios
                                       </button>
                                    
                                    
                                    
                                    
                                    
                                         </center>
                                                  </div>
                              </form>                                           
                                     
                                </div> 
                                     
                                    
                                     
        </div>        
                       
                       
                       
                       
                       
                       
                       
                       
                       
                       
                       
                       
                       
                       
                       
                       
                        <?php  
                        } else {
    echo "<center><h1>Sin Audios Asignados</center><h1>";
}
                        ?>    
                       
        </div>
              

   

        <!-- /span6 --> 
      </div>
      <!-- /row --> 
    </div>
    <!-- /container --> 
  </div>
  <!-- /main-inner --> 
</div>
<!-- /main -->




<!-- /extra -->

<!-- /footer --> 
<!-- Le javascript
================================================== --> 
<!-- Placed at the end of the document so the pages load faster --> 
<script src="./public/jsOld/jquery-1.7.2.min.js"></script> 
<script src="./public/jsOld/excanvas.min.js"></script> 
<script src="./public/jsOld/motores.js"></script>
<script src="./public/jsOld/chart.min.js" type="text/javascript"></script> 
<script src="./public/jsOld/bootstrap.js"></script>
 <script src="./public/jsOld/validarAudios.js"></script>
 <script src="./public/jsOld/pgw/pgwmodal.js"></script>
 <script src="./public/jsOld/pgw/pgwmodal.min.js"></script>
 <script src="./public/jsOld/validarAudios.js"></script>
 <script src="./public/jsOld/asignacion.js"></script>
 
<script language="javascript" type="text/javascript" src="./public/jsOld/full-calendar/fullcalendar.min.js"></script>
 
<script src="./public/jsOld/base.js"></script> 



 <script type="text/javascript" src="./public/js/plugins/datatables/jquery.dataTables.min.js"></script> 
        <script type="text/javascript" src="./public/js/plugins/tableexport/tableExport.js"></script>
		<script type="text/javascript" src="./public/js/plugins/tableexport/jquery.base64.js"></script>
        <script type="text/javascript" src="./public/js/plugins/tableexport/html2canvas.js"></script>
        <script type="text/javascript" src="./public/js/plugins/tableexport/jspdf/libs/sprintf.js"></script>
        <script type="text/javascript" src="./public/js/plugins/tableexport/jspdf/jspdf.js"></script>
        <script type="text/javascript" src="./public/js/plugins/tableexport/jspdf/libs/base64.js"></script>  







       <script>
          $(document).ready(function() {
    
$('#tablaAsignacion').DataTable( {
  
    language: {
            processing:     "Procesando...",
            search:         "Busqueda&nbsp;:",
            lengthMenu:     "Mostar _MENU_ registros",
            info:           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
            infoEmpty:      "Mostrando registros del 0 al 0 de un total de 0 registros",
            infoFiltered:   "(filtrado de un total de  _MAX_ registros)",
            infoPostFix:    "",
            loadingRecords: "Cargando...",
            zeroRecords:    "No hay registros que mostrar",
            emptyTable:     "No hay datos disponibles en la tabla",
            paginate: {
                first:      "Primero",
                previous:   "Anterior",
                next:       "Siguente",
                last:       "Ultimo"
            },
            aria: {
                sortAscending:  ": Activar para ordenar la columna de manera ascendente",
                sortDescending: ": Activar para ordenar la columna de manera descendente"
            }
        } 
} );
    }); 
  </script>
</body>
</html>

