    <!---Inicio -->
            
            
            <!---inicio Estadistica -->
        <div class="span12">
          <div class="widget widget-nopad">
            <div class="widget-header"> <i class="icon-list-alt"></i>
              <h3> Validaciones</h3>
            </div>
            <!-- /widget-header -->
            <div class="widget-content">
              <div class="widget big-stats-container">
                <div class="widget-content">
                  <div id="big_stats" class="cf">
                    <div class="stat"> <i class="icon-bullhorn">Calificados</i> <span class="value"></span> </div>
                    <!-- .stat -->
                    
                    <div class="stat"> <i class="icon-ok">Llamadas Sin Error</i> <span class="value"></span> </div>
                    <!-- .stat -->
                    
                    <div class="stat"> <i class="icon-remove">Llamadas Con Error</i> <span class="value"></span> </div>
                    <!-- .stat -->
                    
                   
                    <!-- .stat --> 
                  </div>
                </div>
                <!-- /widget-content --> 
                
              </div>
            </div>
          </div>
          <!-- /widget -->
         
          <!-- /widget -->
          <!-- /widget --> 
        </div>
   <!---  fin estadistica -->     