<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Dashboard - Bootstrap Admin Template</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<meta name="apple-mobile-web-app-capable" content="yes">
<link href="./public/css/bootstrap.min.css" rel="stylesheet">
<link href="./public/css/bootstrap-responsive.min.css" rel="stylesheet">
<link href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600"
        rel="stylesheet">
<link href="./public/cssOld/font-awesome.css" rel="stylesheet">
<link href="./public/cssOld/style.css" rel="stylesheet">
<link href="./public/cssOld/pages/dashboard.css" rel="stylesheet">
        <link href="./public/cssOld/pgwmodal.min.css" rel="stylesheet">
        <link href="./public/cssOld/pgwmodal.css" rel="stylesheet">
<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>
<body>
     <div class="modal inmodal fade" id="myModal6" tabindex="-1" role="dialog"  aria-hidden="true">
                                <div class="modal-dialog modal-sm">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                                            <h4 class="modal-title" id="alerta">Modal title</h4>
                                        </div>
                                        <div class="modal-body" id="alertar">
                                           
                                        </div>
                                        <div class="modal-footer">
<!--                                            <button type="button" class="btn btn-white" data-dismiss="modal">Cerrar</button>-->
                                            
                                        </div>
                                    </div>
                                </div>
                            </div>
    
    
    
    
    
    
    
    
    
    
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container"> <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"><span
                    class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span> <a class="brand" href="index.html"> <img src="./public/img/logo.png"  alt="Smiley face"> </a>

      <!--/.nav-collapse --> 
    </div>
    <!-- /container --> 
  </div>
  <!-- /navbar-inner --> 
</div>
<!-- /navbar -->
<div class="subnavbar">
  <div class="subnavbar-inner">
    <div class="container">

           <?php 
           if(!empty($getDatosAudios))
                {
               include ('view/encuestas.phtml');
                }else{
             echo "<center><h1>SIN REGISTROS</h1></center> <br><br> <center>   <button  onclick='cerrar()' class='btn btn-danger' id='btnCancelar' name='btnCancelar'  type='button'>Cerrar</button></center>   "
                    ; 
             
                }
               ?>    
 
    </div>

    <!-- /container --> 
  </div>
  <!-- /subnavbar-inner --> 
</div>
<!-- /subnavbar -->
<div class="main">
  <div class="main-inner">
    <div class="container">
      <div class="row">
          <div id="panelPreguntas" style="display:none">
              <form  action="guardarEncuesta.php" id="preguntase" name="preguntase" method="POST">       
                   <div class="span8">
         <table id="datatable-responsive"  class="table table-striped table-bordered" style="height:200px;  overflow-x:hidden">
              </table>
                	<div class="col-sm-4" > 
                            <label><b>Observaciones</b></label>
                             <textarea rows="5" cols="10" id="comentarioEncuesta" name="comentarioEncuesta">
     
</textarea>    
                            </div>        
                       
                       
       <div class="form-group">
                                    <div class="col-sm-4 col-sm-offset-2">
                                        <input type="hidden"    value="<?= $getDatosAudios[0]['agente'] ?>" id="idAgente" name="idAgente">  
                                        <input type="hidden"    value="<?= $getDatosAudios[0]['id'] ?>" id="idAudio" name="idAudio">  
                                        <input type="hidden"    value="<?=  $nombreUser[0]['id']?>" id="idUser" name="idUser">
                                        <input type="hidden"    value="<?= $nombreUser[0]['num_empleado']?>" id="nombreUser" name="nombreUser">
                                        <input type="hidden"  value=""   id="contador" name="contador"> 
                                    <!--    <input tyoe="hidden"   value =""  id="idVariables" name="idVariables">-->
                                     <!--  <button class='btn btn-danger' id='btnCerrar' onclick='cerrar()' name='btnCerrar'  type='button'>Cerrar</button>-->
                                     <div id="buttonGuardar" name="buttonGuardar">     
                                        
                               <!--  <button type="submit" class="btn btn-primary"  id="buttonGuardar" name="buttonGuardar" >
                                        Guardar Evaluacion Prueba
                                       </button>-->
                                <div id="buttonGuardar" name="buttonGuardar"  >
                                
                                    </div>
                                                                       
                                     
                                </div> 
                                     
                                    
                                     
        </div>
              </form>

   

        <!-- /span6 --> 
      </div>
      <!-- /row --> 
    </div>
    <!-- /container --> 
  </div>
  <!-- /main-inner --> 
</div>
<!-- /main -->




<!-- /extra -->

<!-- /footer --> 
<!-- Le javascript
================================================== --> 
<!-- Placed at the end of the document so the pages load faster --> 
<script src="./public/jsOld/jquery-1.7.2.min.js"></script> 
<script src="./public/jsOld/excanvas.min.js"></script> 
<script src="./public/jsOld/chart.min.js" type="text/javascript"></script> 
<script src="./public/jsOld/bootstrap.js"></script>
 <script src="./public/jsOld/validarAudios.js"></script>
 <script src="./public/jsOld/pgw/pgwmodal.js"></script>
 <script src="./public/jsOld/pgw/pgwmodal.min.js"></script>
 <script src="./public/jsOld/validarAudios.js"></script>
<script src="./public/jsOld/base.js"></script> 
<script>

    
    
</script>
</body>
</html>
