<!DOCTYPE html>
<html  class="body-full-height">

<head>

       <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>ECD | Calidad Login</title>



    <link rel="stylesheet" type="text/css" id="theme" href="./public/css/theme-default.css" rel="stylesheet">
     
</head>
  <body style="font-family:'Calisto MT'">
        
        <div class="login-container">
        
            <div class="login-box animated fadeInDown">
                <!--  <h5 class="logo-name"> ECD | CAZ  </h5>-->
			<center>	<img src="./public/img/logo-1.png" width=110  height=80 alt="Smiley face"></center>
                <center> <h3>Bienvenidos  al Sistema de Calidad ECD</h3> 
                 
                 <!-- <p>Perfectamente diseñado para el Control de Encuestas de Call Center.</p>-->
                 <p>Iniciar sesion.</p></center>
                  
                <div class="login-body">
                    <div class="login-title"><strong>Bienvenido</strong> <!-- , Please login --></div>
                    <form id="form_login" name="form_login"  action="login.php"  class="form-horizontal" method="post">
                    <div class="form-group">
                        <div class="col-md-12">
                            <input type="text" id="username" name="username" class="form-control" placeholder="Username"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            <input type="password" id="password" name="password" class="form-control" placeholder="Password"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-6">
                            <!--<a href="#" class="btn btn-link btn-block">Olvidaste tu password?</a>-->
                        </div>
                        <div class="col-md-6">
                      
					<!--   <button class="btn btn-info btn-block" id="enviar" style="background-color:#CCC; border-color:#CCC !important">Entrar</button>-->
                      
                                           <button type="submit">Entrar</button>
                        
                        </div>
                    </div>
                    </form>
                </div>
                <div id="resp" style=" text-align:center; font-size:14px"></div>
                <div class="login-footer">
                    <div class="pull-left">
                        &copy; <?=date('Y')?> Especialistas Contacto Directo. 
                    </div>
                    <div class="pull-right">
                        <!--<a href="#">About</a> |
                        
                        <a href="#">Privacy</a> |
                        <a href="#">Contact Us</a>-->
                    </div>
                </div>
            </div>
            
        </div>
        
    </body>


</html>
