  <ul class="x-navigation x-navigation-horizontal">
               
                    <li class="xn-logo" style=" height:40px; " >
                      <a href="index.php">     
                    <!--  -->   </a>
                   
                        <a href="#" class="x-navigation-control">
                      
                    </a>
                       
                    </li>
                    
                  
                    <!-- <li class="xn-profile">
                        <a href="#" class="profile-mini">
                            <!--<img src="assets/images/users/avatar.jpg" alt="John Doe"/>
                        </a>
                    <div class="profile">
                            <div class="profile-image">
                               <!-- <img src="assets/images/users/avatar.jpg" alt="John Doe"/>
                            </div>
                           
                            <div class="profile-data">
                                <div class="profile-data-name"><?php echo $_SESSION['Nombre_User'] ?></div>
                                <div class="profile-data-title">Web Developer/Designer</div>
                            </div>
                           
                            
                            <div class="profile-controls">
                                <a href="pages-profile.html" class="profile-control-left"><span class="fa fa-info"></span></a>
                                <a href="pages-messages.html" class="profile-control-right"><span class="fa fa-envelope"></span></a>
                            </div>
                        </div> 
                    -->  
                      
                        </li>
                   <li class="xn-title" style="color:#FFF">Menu</li>
                     


                        <li>
                        <a href="monitoreosCalidad.php"><span class="fa fa-users" title="Evaluaci&oacute;n Distribuidores"></span> <span class="xn-text" title="Evaluaci&oacute;n Distribuidores">Evaluacion a Distribuidores</span></a>
                        
                        </li>      
</ul>              
                
                
                