<div class="row">
<div class="col-md-12">
<div class="card">
  <div class="card-header" data-background-color="blue">
      <h4 class="title">Nuevo Usuario</h4>
  </div>
  <div class="card-content table-responsive">
<form class="form-horizontal" role="form" method="post" action="guardarUsuario.php">

  <div class="form-group">
    <label for="inputNoEmpleado" class="col-lg-2 control-label">No Empleado</label>
    <div class="col-lg-9">
       <input type="text" class="form-control" name="noEmple" id="noEmple">
    </div>
  </div>

  <div class="form-group">
    <label for="inputNombreEmple" class="col-lg-2 control-label">Nombre Empleado</label>
    <div class="col-lg-9">
       <input type="text" class="form-control" name="nombreEmple" id="nombreEmple">
    </div>
  </div>    

 <div class="form-group">
    <label for="inputArea" class="col-lg-2 control-label">Departamento</label>
    <div class="col-lg-9">
   <select name="AreaEmple" id="AreaEmple" class="form-control"  onchange="getPuesto()">
                       <option  value = "" selected>Seleccione una Opción</option>
                                   <?php 
                                    if(!empty($datosDepa)){
                                    foreach($datosDepa as $departamentoNombre){
                                        
                                   echo  '<option value="'.$departamentoNombre['id'].'">' . utf8_encode($departamentoNombre['nombre_depa']).'</option>';
                                    
                                    }
                
                                    }else{
                                         echo  '<option value=""> </option>'; 
                                    }
                                    ?> 
 
</select>
    </div>    
  </div>


      <div class="form-group">
    <label for="inputEmail1" class="col-lg-2 control-label">Puesto</label>
    <div class="col-lg-9">
        <select name="puestoEmple" id="puestoEmple" class="form-control" onchange="getArea()" required>
        <option  value = "" selected>Seleccione una Opción</option>                          
</select>
    </div>
  </div>
    
      <div class="form-group">
    <label for="inputArea" class="col-lg-2 control-label">Area</label>
    <div class="col-lg-9">     
        <input  type="text" name="AreaEmpleado" id="AreaEmpleado"  value="" class="form-control" readonly>                                            
</select>
    </div>    
  </div>   
    
    
    
    
    
    

    <div class="form-group">
        <label for="inputIngreso" class="col-lg-2 control-label">Fecha Ingreso</label>
    <div class="col-lg-9">
        <input type="text" class="form-control" name="fechaIngreso" id="fechaIngreso" value="<?php echo date("d/m/Y") ?>" readonly>      
    </div>
    </div>
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
        <input type="hidden" id="idArea" name="idArea" value=""> 
  <button type="submit"  name="Enviar" class="btn btn-default">Guardar Usuario</button>
 <!--<button type="button" onclick="guardarPersonal()"  name="EnviarUsuario"  data-toggle="modal" data-target="#personalSave" class="btn btn-default">Guardar Usuario</button>-->
<!-- <button type="button" onclick="guardarServicio()"  name="Enviar"  data-toggle="modal" data-target="#myModal6" class="btn btn-default">Guardar Servicio</button>
    </div>
  </div>
</form>
</div>
</div>
</div>