<br>
<div class="row">
<div class="col-md-12">
<div class="card">
  <div class="card-header" data-background-color="blue">
      <h4 class="title">Actualizacion de Datos</h4>
  </div>
  <div class="card-content table-responsive">
<form class="form-horizontal" role="form" method="post" action="guardarUsuario.php">

  <div class="form-group">
    <label for="inputNoEmpleado" class="col-lg-2 control-label" >No Empleado</label>
    <div class="col-lg-9">
        <input type="text" class="form-control" name="noEmpleUpdate" id="noEmpleUpdate" value ="<?=$getDatosActualizar[0]['username'];?>" required readonly>
    </div>
  </div>

  <div class="form-group">
    <label for="inputNombreEmple" class="col-lg-2 control-label">Nombre Empleado</label>
    <div class="col-lg-9">
       <input type="text" class="form-control" name="nombreEmpleUpdate" id="nombreEmpleUpdate" value =" <?=$getDatosActualizar[0]['nombre'];?>" required>
    </div>
  </div>    

 <div class="form-group">
    <label for="inputArea" class="col-lg-2 control-label">Departamento</label>
    <div class="col-lg-9">
   <select name="departamentoValue" id="departamentoValue" class="form-control"  onchange="getArea()"  required>
                       <option  value = "">Seleccione una Opción</option>
   <?=$getDatosActualizar[0]['identificadorarea'] == 1 ? ' <option value="1" selected>Operacion</option> 
      <option value="2">Administrativa</option>' :  ' <option value="1">Operacion</option> 
      <option value="2" selected >Administrativa</option>' 
            ?>       
 
</select>
    </div>    
  </div>
     <div class="form-group">
    <label for="inputArea" class="col-lg-2 control-label">Area</label>
    <div class="col-lg-9">
   <select name="AreaEmple" id="AreaEmple" class="form-control"   onchange="getPuesto()" required>
                
                  <option  value = "<?=$getDatosActualizar[0]['cat_area_id'];?>" selected><?=$getDatosActualizar[0]['area'];?></option>
                          
</select>
    </div>    
  </div>
      <div class="form-group">
    <label for="inputEmail1" class="col-lg-2 control-label">Puesto</label>
    <div class="col-lg-9">
   <select name="puestoEmple" id="puestoEmple" class="form-control" required>     
    <option  value = "<?=$getDatosActualizar[0]['cat_puesto_id'];?>" selected><?=$getDatosActualizar[0]['puesto'];?></option>
                                 
</select>
    </div>
  </div>
    <div class="form-group">
    <label for="inputArea" class="col-lg-2 control-label">Estatus</label>
    <div class="col-lg-9">
        <select name="idEstatusPerson" id="idEstatusPerson" class="form-control"   disabled required>
                 <option  value = "" selected>Seleccione una Opción</option>
         <?= $getDatosActualizar[0]['statusPerson'] != 1  ? "<option  value = '1'>Activar</option>":"<option  value = '2'>Baja</option>"  ?>
   
                       
</select>
    </div> 
    <br>
    <label class="checkbox-inline">
          <input type="checkbox" value="1" id="Checkbox3" name="Checkbox3" >Activar</label>   
  </div>
     
    
    
    
    
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
        <input type="hidden"  id="idPersonalUp" name="idPersonalUp" value="<?=$idPersonal?>">
 <!--  <button type="submit"  name="Enviar" class="btn btn-default">Guardar Usuario</button>-->
 <button type="button" onclick="updateDatePerson()" id="UpdateUsuario"  name="UpdateUsuario"  class="btn btn-info">Actualizar Datos</button>
 <button type="button"  name="cerrarModal" id="cerrarModal" onclick="$.pgwModal('close');"  class="btn btn-danger"   >Cerrar</button>
<!-- <button type="button" onclick="guardarServicio()"  name="Enviar"  data-toggle="modal" data-target="#myModal6" class="btn btn-default">Guardar Servicio</button>-->
    </div>
  </div>
</form>
</div>
</div>
</div>
</div>