          <div class="container-fluid">
<div class="row">

						<div class="col-lg-3 col-md-6 col-sm-6">
							<div class="card card-stats">
								<div class="card-header" data-background-color="orange">
									<i class="fa  fa-clock-o"></i>
								</div>
								<div class="card-content">
									<p class="category">Pendientes</p>
									<h3 class="title"><?= $estadistica[0]['Pendientes']; ?></h3>
								</div>
							</div>
						</div>
						<div class="col-lg-3 col-md-6 col-sm-6">
							<div class="card card-stats">
								<div class="card-header" data-background-color="red">
									<i class="fa fa-th-list"></i>
								</div>
								<div class="card-content">
									<p class="category">Abiertos</p>
									<h3 class="title"><?= $estadistica[0]['Abiertos']; ?></h3>
								</div>
							</div>
						</div>
					</div>
</div>
       