
<!DOCTYPE html>
<html lang="en">
    <head>        
        <!-- META SECTION -->
        <title>Calidad | ECD</title>
          
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        
        <link rel="icon" href="favicon.ico" type="image/x-icon" />
        <!-- END META SECTION -->
        
        <!-- CSS INCLUDE -->        
        <link rel="stylesheet" type="text/css" id="theme" href="./public/css/theme-default.css"/>
          <link href="./public/css/list.css" rel="stylesheet">
        <link href="./public/js/plugins/modal/pgwmodal.min.css" rel="stylesheet">

        <!-- EOF CSS INCLUDE -->                                     
        
      
        
          
		
        
    </head>
      <body>

        <!-- START PAGE CONTAINER -->
        <div  class="page-container page-navigation-toggled page-container-wide">
            <!-- START PAGE SIDEBAR -->
            <div class="page-sidebar">
                <!-- START X-NAVIGATION -->

                
                
                <?php include ($datosVista['menu']); ?>  
                <!--- Menu -->
                
                
                
                
                
                <!-- END X-NAVIGATION -->
            </div>
            <!-- END PAGE SIDEBAR -->
            
            <!-- PAGE CONTENT -->
            <div class="page-content">
                 
                <?php include ($datosVista['template']); ?>  
                
                <!---contenido --->
                
              
                
                
            <!-- END PAGE CONTENT -->
        </div>
        <!-- END PAGE CONTAINER -->    
        
        

        <!-- MESSAGE BOX-->
        <div class="message-box animated fadeIn" data-sound="alert" id="mb-signout">
            <div class="mb-container">
                <div class="mb-middle">
                    <div class="mb-title"><span class="fa fa-sign-out"></span> ENTRAR <strong> SALIR</strong> ?</div>
                    <div class="mb-content">
                        <p>Deseas salir del sistema?</p>                    
                        <p>Presiona NO si deseas salir . Presiona SI para salir.</p>
                    </div>
                    <div class="mb-footer">
                        <div class="pull-right">
                            <a href="logut.php" class="btn btn-success btn-lg">Si</a>
                            <button class="btn btn-default btn-lg mb-control-close" id="Nocerrar" style="z-index:1000">No</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- END MESSAGE BOX-->

        <!-- START PRELOADS -->
      
        <!-- END PRELOADS -->             
   <!-- START SCRIPTS -->
        <!-- START PLUGINS -->
        <script type="text/javascript" src="./public/js/plugins/jquery/jquery.min.js"></script>
        <script type="text/javascript" src="./public/js/plugins/jquery/jquery-ui.min.js"></script>
        <script type="text/javascript" src="./public/js/plugins/bootstrap/bootstrap.min.js"></script>
        <script type="text/javascript" src="./public/js/listDinamico.js"></script>   
         <script type="text/javascript" src="./public/js/querys/campanas.js"></script>  
        <!--Graficas -->
        <script src="./public/js/plugins/amcharts2/amcharts/amcharts.js"></script>
        <script src="./public/js/plugins/amcharts2/amcharts/serial.js"></script>
        <script src="./public/js/plugins/amcharts2/amcharts/themes/light.js"></script>
        <script src="./public/js/plugins/amcharts2/amcharts/pie.js"></script>
        <!--Fin Graficas
        
        <!-- END PLUGINS -->

        <!-- THIS PAGE PLUGINS -->
        <script type='text/javascript' src='./public/js/plugins/icheck/icheck.min.js'></script>
        <script type="text/javascript" src="./public/js/plugins/mcustomscrollbar/jquery.mCustomScrollbar.min.js"></script>
        
       
        

        <script type="text/javascript" src="./public/js/plugins/datatables/jquery.dataTables.min.js"></script> 
        <script type="text/javascript" src="./public/js/plugins/tableexport/tableExport.js"></script>
		<script type="text/javascript" src="./public/js/plugins/tableexport/jquery.base64.js"></script>
        <script type="text/javascript" src="./public/js/plugins/tableexport/html2canvas.js"></script>
        <script type="text/javascript" src="./public/js/plugins/tableexport/jspdf/libs/sprintf.js"></script>
        <script type="text/javascript" src="./public/js/plugins/tableexport/jspdf/jspdf.js"></script>
        <script type="text/javascript" src="./public/js/plugins/tableexport/jspdf/libs/base64.js"></script>  
        
        
         <script type="text/javascript" src="./public/js/plugins/bootstrap/bootstrap-datepicker.js"></script>
        <script type="text/javascript" src="./public/js/plugins/bootstrap/bootstrap-timepicker.min.js"></script>
        <script type="text/javascript" src="./public/js/plugins/bootstrap/bootstrap-colorpicker.js"></script>
        <script type="text/javascript" src="./public/js/plugins/bootstrap/bootstrap-file-input.js"></script>
        <script type="text/javascript" src="./public/js/plugins/bootstrap/bootstrap-select.js"></script>
        <script type="text/javascript" src="./public/js/plugins/tagsinput/jquery.tagsinput.min.js"></script>
        <!-- END THIS PAGE PLUGINS -->       
        
        
        <script type="text/javascript" src="./public/js/plugins/morris/raphael-min.js"></script>
        <script type="text/javascript" src="./public/js/plugins/morris/morris.min.js"></script>
        
      
       
        <!-- END PAGE PLUGINS -->       

        <!-- START TEMPLATE -->
        <script type="text/javascript" src="./public/js/plugins.js"></script>        
        <script type="text/javascript" src="./public/js/actions.js"></script>        
        <!-- END TEMPLATE -->
    <!-- END SCRIPTS -->  
	    <script src="./public/js/plugins/modal/pgwmodal.min.js"></script>        

           <script>
          $(document).ready(function() {
    
$('#tabla_campana').DataTable( {
  
    language: {
            processing:     "Procesando...",
            search:         "Busqueda&nbsp;:",
            lengthMenu:     "Mostar _MENU_ registros",
            info:           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
            infoEmpty:      "Mostrando registros del 0 al 0 de un total de 0 registros",
            infoFiltered:   "(filtrado de un total de  _MAX_ registros)",
            infoPostFix:    "",
            loadingRecords: "Cargando...",
            zeroRecords:    "No hay registros que mostrar",
            emptyTable:     "No hay datos disponibles en la tabla",
            paginate: {
                first:      "Primero",
                previous:   "Anterior",
                next:       "Siguente",
                last:       "Ultimo"
            },
            aria: {
                sortAscending:  ": Activar para ordenar la columna de manera ascendente",
                sortDescending: ": Activar para ordenar la columna de manera descendente"
            }
        } 
} );







$('#tabla_asignacion').DataTable( {
  
    language: {
            processing:     "Procesando...",
            search:         "Busqueda&nbsp;:",
            lengthMenu:     "Mostar _MENU_ registros",
            info:           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
            infoEmpty:      "Mostrando registros del 0 al 0 de un total de 0 registros",
            infoFiltered:   "(filtrado de un total de  _MAX_ registros)",
            infoPostFix:    "",
            loadingRecords: "Cargando...",
            zeroRecords:    "No hay registros que mostrar",
            emptyTable:     "No hay datos disponibles en la tabla",
            paginate: {
                first:      "Primero",
                previous:   "Anterior",
                next:       "Siguente",
                last:       "Ultimo"
            },
            aria: {
                sortAscending:  ": Activar para ordenar la columna de manera ascendente",
                sortDescending: ": Activar para ordenar la columna de manera descendente"
            }
        } 
} );




    }); 
  </script>     
    </body>
</html>






