
<div  class="row">
        <div class="col-md-6">
        <div class="card">
            <div class="card-header" data-background-color="blue">
                <h4 class="title">Departamento Con mas Tickets Solicitados</h4>
            </div>
            
            <div id="chartdivBarras">                   
               
        </div>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
                        <br>
            <br>
            <br>
            <br>
            <br>
                                    <br>
            <br>
            <br>
            <br>
            
                                             <br>
            <br>
            <br>
            <br>
            


            
        </div>
</div>
  <div class="col-md-6">
        <div class="card">
            <div class="card-header" data-background-color="blue">
                <h4 class="title">Levatamiento de Tickets al Dia</h4>
            </div>
            <div class="card-content table-responsive">                   
<div id="chartdiv"></div>

</div>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br>
                                <br>
                <br>
                <br>
                                <br>
                <br>
                <br>
                                <br>
                <br>
                <br>
                                <br>
                              
            </div>
        </div> 
</div>

<div class="row">
     <div class="col-md-6">
        <div class="card">
            <div class="card-header" data-background-color="blue">
                <h4 class="title">Tipo de Servicio mas Solicitdado</h4>
            </div>
            <div class="card-content table-responsive" style="height:310px; overflow-y: scroll; overflow-x:hidden">                   
                <table id="serviceFrecuencia" class="table table-bordered table-hover" cellspacing="0" width="100%">
                    <tr> 
                        <th>Servicio</th>
                        <th>Servicios Realizados</th>
                    </tr>
                    <tbody>
                        <?php
                        foreach ($soportesFrecuencia as $frecuencia)
                        {
                            ?>
                            <tr>
                            <td><?php echo $frecuencia['servicio'];?> </td>
                            <td><?php echo $frecuencia['total'];?> </td>                                
                        </tr>
                      <?php
                      
                        }
                        ?>
                        
                    </tbody>
                </table>
        </div>
    </div>
</div> 
      <div class="col-md-6">
        <div class="card">
            <div class="card-header" data-background-color="blue">
                <h4 class="title">Usuarios Con mas Cantidad de Tickets</h4>
            </div>
            <div class="card-content table-responsive" style="height:310px; overflow-y: scroll; overflow-x:hidden">                   
                <table id="serviceClient" class="table table-bordered table-hover" cellspacing="0" width="100%">
                    <tr> 
                        <th>Nombre Usuario</th>
                        <th>Cantidad de Tickets</th>
                    </tr>
                    <tbody>
                        <?php
                        foreach ($soporteClientFrencuencia as $frecuencia)
                        {
                            ?>
                            <tr>
                            <td><?php echo $frecuencia['nombre_personal'];?> </td>
                            <td><?php echo $frecuencia['total'];?> </td>                                
                        </tr>
                      <?php
                      
                        }
                        ?>
                        
                    </tbody>
                    
                    
                    
                    
                </table>
        </div>
    </div>
</div>
</div>
