<!DOCTYPE html>
<html>
<head>

	<meta charset="utf-8">
		<link rel="stylesheet" href="./public/css/bootstrap.min.css">
		<link rel="stylesheet" href="./public/css/bootstrap-responsive.min.css">
                <link rel="stylesheet" href="./public/css/maruti-login.css">
	<title>HELP DESK | ECD </title>
</head>
<body 	   >


    
    
   <?php include ($datos_vista['template']); ?>
    
    
    
    
  <script src="./public/js/jquery.min.js"></script>  
  <script src="./public/js/maruti.login.js"></script> 
</body>
        </html>