  <!doctype html>

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

  <title>HELP DESK | ECD</title>

  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />
    <link href="./public/css/assets/css/bootstrap.min.css" rel="stylesheet" />
    <link href="./public/css/assets/css/material-dashboard.css" rel="stylesheet"/>
    <link href="./public/css/linea.css" rel="stylesheet"/>
    <link href="./public/css/pgwmodal.css" rel="stylesheet"/>
     <link href="./public/css/pgwmodal.min.css" rel="stylesheet"/>
    <link href="./public/css/assets/font-awesome/css/font-awesome.min.css" rel="stylesheet">
  <script src="./public/js/js/jquery.min.js" type="text/javascript"></script>
</head>

<body>

  <div class="wrapper">
     <!-- <div class="main-panel">
      <div class="content">
      <div class="container-fluid"-->
          <?php include ($datosVista['template']); ?>
          <!--- estadistica -->
   <!--</div>
      </div>
    </div>-->
  </div>
</body>
  <!--   Core JS Files   -->
  <script src="./public/js/js/bootstrap.min.js" type="text/javascript"></script>
  <script src="./public/js/js/material.min.js" type="text/javascript"></script>
 <script src="./public/js/querys/guardarSoporte.js" type="text/javascript"></script>
 <script  src="./public/js/querys/getSoporte.js" type="text/javascript"></script>
 <script  src="./public/js/querys/updateDatos.js" type="text/javascript"></script>
   <script src="./public/js/dataTables/jquery.dataTables.min.js" type="text/javascript"></script>
  <!--  Charts Plugin -->
  <script src="./public/js/js/chartist.min.js"></script>
  <script src="./public/js/pgw/pgwmodal.js"></script>
  <script src="./public/js/pgw/pgwmodal.min.js"></script>
  <!--  Notifications Plugin    -->
  <script src="./public/js/js/bootstrap-notify.js"></script>

  <!--  Google Maps Plugin    -->
  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js"></script>

  <!-- Material Dashboard javascript methods -->
  <script src="./public/js/js/material-dashboard.js"></script>

     <link href="./public/css/jquery.dataTables.min.css" rel="stylesheet">
  <!-- Material Dashboard DEMO methods, don't include it in your project! -->
  <script src="./public/js/js/demo.js"></script>
  <script> 
  $(document).ready(function(){
    $('#Checkbox3').click(function(){    
        if($('input[name=Checkbox3]').is(':checked')){
       $("#idEstatusPerson").attr("disabled", false);
        $("#idEstatusPerson").attr("required", false);
            //return true;
           
        }
        else{
         $("#idEstatusPerson").attr("disabled", true);  
         $("#idEstatusPerson").attr("required", true);
           // alert('Debe aceptar la politica de privacidad');
           // return false;
        }
    });

    
    
    
    
    
    
    
    
});

  </script>
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
</html>    