<!doctype html>

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

  <title>HELP DESK | ECD</title>

  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />
    <link href="./public/css/assets/css/bootstrap.min.css" rel="stylesheet" />
    <link href="./public/css/assets/css/material-dashboard.css" rel="stylesheet"/>
    <link href="./public/css/assets/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="./public/css/jquery.dataTables.min.css" rel="stylesheet">
    <link href="./public/css/linea.css" rel="stylesheet"/>
    <script src="./public/js/js/jquery.min.js" type="text/javascript"></script>
     <link href="./public/css/pgwmodal.css" rel="stylesheet"/>
</head>

<body>

  <div class="wrapper">

       <div class="modal inmodal fade" id="myModal7" tabindex="-1" role="dialog"  aria-hidden="true">
                                <div class="modal-dialog modal-sm">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            
                                            <h4 class="modal-title" id="alertatitulos2"></h4>
                                        </div>
                                        <div class="modal-body" id="alertarte2">
                                           
                                        </div>
                                        <div class="modal-footer">
<!--                                            <button type="button" class="btn btn-white" data-dismiss="modal">Cerrar</button>-->
                                            
                                        </div>
                                    </div>
                                </div>
                            </div>
      
      
      
      
      
      
      
      
      
      
      
      
      
      <div class="sidebar" data-color="blue">
      <div class="logo">
        <a href="servicioAdmin.php" class="simple-text">
         <img src="./public/img/logo.png"  width="250" alt="Logo"/>
        </a>
      </div>
        <div class="sidebar-wrapper">
              <ul class="nav">
                 
                  <li>
                      <a href="servicioAdmin.php">
                          <i class="fa fa fa-home"></i>
                          <p>Inicio</p>
                      </a>
                  </li>
              </ul>
            <ul class="nav">
                 
                  <li>
                      <a href="historySuperAdmin.php">
                          <i class="fa fa-ticket"></i>
                          <p>Servicios Diarios</p>
                      </a>
                  </li>
              </ul> 
          
                      <ul class="nav">
                 
                  <li>
                      <a href="usuariosAltasBaj.php">
                          <i class="fa fa-group"></i>
                          <p>Usuarios</p>
                      </a>
                  </li>
              </ul>  
            
            
            
            
            
         <ul class="nav">
                 
                  <li>
                      <a href="directorio.php">
                          <i class="fa fa-book"></i>
                          <p>Directorio</p>
                      </a>
                  </li>
              </ul>     
        </div>
      </div>

      <div class="main-panel">
      <nav class="navbar navbar-transparent navbar-absolute">
        <div class="container-fluid">
          <div class="navbar-header">
              <div class="navbar-brand">
                <b id="fechaactual">  </b>  <b id="reloj"></b>
            </div>   

              
              
            
                    <div class="timeline">
  <ol>
<li>
      <div>
        <time>Solicitud</time>
      </div>
    </li>
    <li>
      <div>
        <time>Atencion</time>
      </div>
    </li>
    <li>
      <div>
        <time>Proceso</time>
      </div>
    </li>
    <li>
      <div>
        <time>Terminado</time>
      </div>
    </li>
    <li></li>

  </ol>
            </div>   
  
            <button type="button" class="navbar-toggle" data-toggle="collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button> 
          </div>
          <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="fa fa-user"></i>
                  <?= $datosVista['nombre']; ?>
                </a>
                <ul class="dropdown-menu">
                  <li><a href="logut.php">Salir</a></li>
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </nav>

      <div class="content">
      <div class="container-fluid">
          <?php include ($datosVista['estadistica']); ?>
          <?php include ($datosVista['template']); ?>
          <!--- estadistica -->



</div>
      </div>

      <footer class="footer">
        <div class="container-fluid">
          <p class="copyright pull-right">
        DR &copy; ESPECIALISTAS CONTACTO DIRECTO ECD, S.A. DE C.V. M&Eacute;XICO, CDMX, 2017. TODOS LOS DERECHOS RESERVADOS.		   
          </p>
        </div>
      </footer>
    </div>
  </div>
</body>

  <!--   Core JS Files   -->
  <script src="./public/js/js/bootstrap.min.js" type="text/javascript"></script>
  <script src="./public/js/js/material.min.js" type="text/javascript"></script>
 <script src="./public/js/querys/guardarSoporte.js" type="text/javascript"></script>
  <script src="./public/js/dataTables/jquery.dataTables.min.js" type="text/javascript"></script>
  <script src="./public/js/querys/getSoporte.js" type="text/javascript"></script>
  <!--  Charts Plugin -->
  <script src="./public/js/js/chartist.min.js"></script>
  <script src="./public/js/querys/updateDatos.js"></script>
   <script src="./public/js/pgw/pgwmodal.js"></script>
  <script src="./public/js/pgw/pgwmodal.min.js"></script>
  <!--  Notifications Plugin    -->
  <script src="./public/js/js/bootstrap-notify.js"></script>

  <!--  Google Maps Plugin    -->
  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js"></script>

  <!-- Material Dashboard javascript methods -->
  <script src="./public/js/js/material-dashboard.js"></script>

  <!-- Material Dashboard DEMO methods, don't include it in your project! -->
  <script src="./public/js/js/demo.js"></script>

  <script>
          $(document).ready(function() {
    
$('#serviceAdmin').DataTable( {
    language: {
            processing:     "Procesando...",
            search:         "Busqueda&nbsp;:",
            lengthMenu:     "Mostar _MENU_ registros",
            info:           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
            infoEmpty:      "Mostrando registros del 0 al 0 de un total de 0 registros",
            infoFiltered:   "(filtrado de un total de  _MAX_ registros)",
            infoPostFix:    "",
            loadingRecords: "Cargando...",
            zeroRecords:    "No hay registros que mostrar",
            emptyTable:     "No hay datos disponibles en la tabla",
            paginate: {
                first:      "Primero",
                previous:   "Anterior",
                next:       "Siguente",
                last:       "Ultimo"
            },
            aria: {
                sortAscending:  ": Activar para ordenar la columna de manera ascendente",
                sortDescending: ": Activar para ordenar la columna de manera descendente"
            }
        } 
} );

$('#serviceadminH').DataTable({
    language: {
            processing:     "Procesando...",
            search:         "Busqueda&nbsp;:",
            lengthMenu:     "Mostar _MENU_ registros",
            info:           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
            infoEmpty:      "Mostrando registros del 0 al 0 de un total de 0 registros",
            infoFiltered:   "(filtrado de un total de  _MAX_ registros)",
            infoPostFix:    "",
            loadingRecords: "Cargando...",
            zeroRecords:    "No hay registros que mostrar",
            emptyTable:     "No hay datos disponibles en la tabla",
            paginate: {
                first:      "Primero",
                previous:   "Anterior",
                next:       "Siguente",
                last:       "Ultimo"
            },
            aria: {
                sortAscending:  ": Activar para ordenar la columna de manera ascendente",
                sortDescending: ": Activar para ordenar la columna de manera descendente"
            }
        } 
} );

$('#directoryL').DataTable({
    language: {
            processing:     "Procesando...",
            search:         "Busqueda&nbsp;:",
            lengthMenu:     "Mostar _MENU_ registros",
            info:           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
            infoEmpty:      "Mostrando registros del 0 al 0 de un total de 0 registros",
            infoFiltered:   "(filtrado de un total de  _MAX_ registros)",
            infoPostFix:    "",
            loadingRecords: "Cargando...",
            zeroRecords:    "No hay registros que mostrar",
            emptyTable:     "No hay datos disponibles en la tabla",
            paginate: {
                first:      "Primero",
                previous:   "Anterior",
                next:       "Siguente",
                last:       "Ultimo"
            },
            aria: {
                sortAscending:  ": Activar para ordenar la columna de manera ascendente",
                sortDescending: ": Activar para ordenar la columna de manera descendente"
            }
        } 
} );


$('#usuarioRecepcion').DataTable({
    language: {
            processing:     "Procesando...",
            search:         "Busqueda&nbsp;:",
            lengthMenu:     "Mostar _MENU_ registros",
            info:           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
            infoEmpty:      "Mostrando registros del 0 al 0 de un total de 0 registros",
            infoFiltered:   "(filtrado de un total de  _MAX_ registros)",
            infoPostFix:    "",
            loadingRecords: "Cargando...",
            zeroRecords:    "No hay registros que mostrar",
            emptyTable:     "No hay datos disponibles en la tabla",
            paginate: {
                first:      "Primero",
                previous:   "Anterior",
                next:       "Siguente",
                last:       "Ultimo"
            },
            aria: {
                sortAscending:  ": Activar para ordenar la columna de manera ascendente",
                sortDescending: ": Activar para ordenar la columna de manera descendente"
            }
        } 
} );







});
  </script>
 <script type="text/javascript">
function startTime(){
today=new Date();
d=today.getDay();
mes=today.getMonth();
y=today.getFullYear();
h=today.getHours();
m=today.getMinutes();
s=today.getSeconds();
m=checkTime(m);
s=checkTime(s);                            
document.getElementById('reloj').innerHTML= h+":"+m+":"+s;
t=setTimeout('startTime()',500);}
function checkTime(i)
{if (i<10) {i="0" + i;}return i;}
window.onload=function(){startTime();}
</script>

<script type="text/javascript">
//<![CDATA[
var date = new Date();
var d  = date.getDate();
var day = (d < 10) ? '0' + d : d;
var m = date.getMonth() + 1;
var month = (m < 10) ? '0' + m : m;
var yy = date.getYear();
var year = (yy < 1000) ? yy + 1900 : yy;
document.getElementById('fechaactual').innerHTML = day + "/" + month + "/" + year;

</script>

  </script>
</html>